- name: "Installer Apache et PHP{{ php_version }}"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - apache2
    - "php{{ php_version }}"
  when: ansible_facts['os_family'] == "Debian"

- name: Secure OS info
  ansible.builtin.lineinfile:
    path: /etc/apache2/conf-available/security.conf
    regexp: '^ServerTokens '
    line: ServerTokens Minimal
  notify:
    - Restart apache

- name: Secure server signature
  ansible.builtin.lineinfile:
    path: /etc/apache2/conf-available/security.conf
    regexp: '^ServerSignature '
    line: ServerSignature Off
  notify:
    - Restart apache

- name: S'assurer qu'Apache est démarré sur Debian
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
  when: ansible_facts['os_family'] == "Debian"

